"""WidgetNode model - nodes containing visualizations (AI-generated HTML/CSS/JS)."""
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import String, Text, Integer, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base_node import BaseNode

if TYPE_CHECKING:
    pass


class WidgetNode(BaseNode):
    """WidgetNode - contains visualization generated by AI from DataNode."""
    
    __tablename__ = "widget_nodes"
    
    # Primary key (inherited from BaseNode)
    id: Mapped[UUID] = mapped_column(ForeignKey("nodes.id"), primary_key=True)
    
    # Identification
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)  # User prompt describing widget
    
    # AI-generated code
    html_code: Mapped[str] = mapped_column(Text, nullable=False)
    css_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    js_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Configuration
    config: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)  # Additional settings
    
    # Auto-refresh configuration (via VISUALIZATION edge)
    auto_refresh: Mapped[bool] = mapped_column(default=True)
    refresh_interval: Mapped[int | None] = mapped_column(Integer, nullable=True)  # seconds
    
    # AI generation metadata
    generated_by: Mapped[str | None] = mapped_column(String(50), nullable=True)  # "reporter_agent", "user"
    generation_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)  # Original user prompt
    
    # Polymorphic configuration
    __mapper_args__ = {
        "polymorphic_identity": "widget_node",
    }
    
    def __repr__(self):
        return f"<WidgetNode(id={self.id}, name={self.name})>"
