/**
 * JSON Source Dialog - диалог для загрузки JSON файлов.
 */
import { useState, useEffect, useMemo, useRef } from 'react'
import { ChevronDown, ChevronRight, FileJson, Plus } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { SourceType } from '@/types'
import { notify } from '@/store/notificationStore'
import { filesAPI } from '@/services/api'
import { cn } from '@/lib/utils'
import { BaseSourceDialog } from './BaseSourceDialog'
import { useSourceDialog } from './useSourceDialog'
import { SourceDialogProps } from './types'

interface MappingColumn {
    name: string
    type: string
    path: string
    nullable?: boolean
    /** Роль ключа (PK/FK) и таблица; для полей данных — путь и принадлежность к таблице. */
    description?: string
}

interface MappingTable {
    id: string
    name: string
    base_path: string
    columns: MappingColumn[]
    pk?: { column: string; strategy?: string }
    fk?: Array<{ column: string; ref_table: string; ref_column: string }>
}

interface SchemaNode {
    path: string
    node_kind: string
    value_types: string[]
    cardinality?: string
}

interface SchemaFieldOption {
    absolutePath: string
    relativePath: string
    inferredType: string
}

const FIELD_ALIASES: Record<string, string> = {
    doktype: 'doktype',
    'докtype': 'doktype',
}

function describeDataColumn(tableId: string, tableName: string, relativePath: string) {
    return (
        `Поле данных из JSON по пути ${relativePath}; относится к таблице «${tableName}» (id=${tableId}). Не ключ.`
    )
}

export function JSONSourceDialog({
    open,
    onOpenChange,
    initialPosition,
    existingSource,
    mode = 'create'
}: SourceDialogProps) {
    const [file, setFile] = useState<File | null>(null)
    const [isUploading, setIsUploading] = useState(false)
    const [mappingTables, setMappingTables] = useState<MappingTable[]>([])
    const [schemaNodes, setSchemaNodes] = useState<SchemaNode[]>([])
    const [activeTableId, setActiveTableId] = useState<string>('')
    const [quickSchemaNodes, setQuickSchemaNodes] = useState<SchemaNode[]>([])
    const [quickSchemaError, setQuickSchemaError] = useState<string | null>(null)
    const [quickJsonData, setQuickJsonData] = useState<any | null>(null)
    const [expandedJsonNodes, setExpandedJsonNodes] = useState<Set<string>>(new Set(['$']))
    const [editingTableId, setEditingTableId] = useState<string | null>(null)
    const [editingTableName, setEditingTableName] = useState<string>('')
    const [pendingColumnScrollTableId, setPendingColumnScrollTableId] = useState<string | null>(null)
    const [autoGeneratedFileKey, setAutoGeneratedFileKey] = useState<string>('')
    const activeColumnsScrollRef = useRef<HTMLDivElement | null>(null)

    const { isLoading, create, update } = useSourceDialog({
        sourceType: SourceType.JSON,
        onClose: () => {
            setFile(null)
            setMappingTables([])
            setSchemaNodes([])
            setActiveTableId('')
            setQuickSchemaNodes([])
            setQuickSchemaError(null)
            setQuickJsonData(null)
            setExpandedJsonNodes(new Set(['$']))
            setEditingTableId(null)
            setEditingTableName('')
            setAutoGeneratedFileKey('')
            onOpenChange(false)
        },
        position: initialPosition,
    })

    const normalizeMappingTables = (raw: any): MappingTable[] => {
        if (!Array.isArray(raw)) return []
        return raw
            .filter((table) => table && typeof table === 'object')
            .map((table, idx) => ({
                id: String(table.id || `table_${idx + 1}`),
                name: String(table.name || table.id || `table_${idx + 1}`),
                base_path: String(table.base_path || '$'),
                pk: table.pk && typeof table.pk === 'object'
                    ? {
                        column: String(table.pk.column || `${String(table.id || `table_${idx + 1}`)}_id`),
                        strategy: table.pk.strategy ? String(table.pk.strategy) : 'surrogate_uuid',
                    }
                    : undefined,
                fk: Array.isArray(table.fk)
                    ? table.fk
                        .filter((entry: any) => entry && typeof entry === 'object')
                        .map((entry: any) => ({
                            column: String(entry.column || ''),
                            ref_table: String(entry.ref_table || ''),
                            ref_column: String(entry.ref_column || ''),
                        }))
                    : undefined,
                columns: Array.isArray(table.columns)
                    ? table.columns
                        .filter((col: any) => col && typeof col === 'object')
                        .map((col: any, colIdx: number) => ({
                            name: String(col.name || `column_${colIdx + 1}`),
                            type: String(col.type || 'text'),
                            path: String(col.path || '$'),
                            nullable: col.nullable !== false,
                            description:
                                typeof col.description === 'string' && col.description.trim()
                                    ? col.description
                                    : describeDataColumn(
                                          String(table.id || `table_${idx + 1}`),
                                          String(table.name || table.id || `table_${idx + 1}`),
                                          String(col.path || '$'),
                                      ),
                        }))
                    : [],
            }))
    }

    const normalizeSchemaNodes = (raw: any): SchemaNode[] => {
        if (!Array.isArray(raw)) return []
        return raw
            .filter((node) => node && typeof node === 'object' && typeof node.path === 'string')
            .map((node) => ({
                path: String(node.path),
                node_kind: String(node.node_kind || 'unknown'),
                value_types: Array.isArray(node.value_types) ? node.value_types.map(String) : [],
                cardinality: node.cardinality ? String(node.cardinality) : undefined,
            }))
    }

    const buildMappingSpecPayload = () => ({
        version: '1.0',
        tables: mappingTables.map((table) => ({
            id: table.id,
            name: table.name,
            base_path: table.base_path,
            pk: table.pk || { column: `${table.id}_id`, strategy: 'surrogate_uuid' },
            fk: table.fk || [],
            columns: table.columns.map((column) => ({
                name: column.name,
                type: column.type || 'text',
                path: column.path,
                nullable: column.nullable !== false,
                description:
                    column.description?.trim() ||
                    describeDataColumn(table.id, table.name, column.path),
            })),
        })),
    })

    const activeTable = mappingTables.find((table) => table.id === activeTableId) || mappingTables[0] || null
    const effectiveSchemaNodes = schemaNodes.length > 0 ? schemaNodes : quickSchemaNodes
    const schemaPathSet = useMemo(() => new Set(effectiveSchemaNodes.map((node) => node.path)), [effectiveSchemaNodes])
    const arrayBasePathOptions = useMemo(() => {
        const arrayPaths = effectiveSchemaNodes
            .filter((node) => node.node_kind === 'array')
            .map((node) => (node.path.endsWith('[*]') ? node.path : `${node.path}[*]`))
        const rowItemPaths = effectiveSchemaNodes
            .filter((node) => node.node_kind === 'object' && node.path.endsWith('[*]') && node.path !== '$')
            .map((node) => node.path)
        const options = [...arrayPaths, ...rowItemPaths]
            .filter((path, idx, arr) => arr.indexOf(path) === idx)
            .sort((a, b) => a.length - b.length)
        return options
    }, [effectiveSchemaNodes])
    const arrayBasePathSet = useMemo(() => new Set(arrayBasePathOptions), [arrayBasePathOptions])
    const derivedSourceName = useMemo(() => {
        const meaningfulPath =
            effectiveSchemaNodes
                .find((node) => node.path.includes('[*]') && node.node_kind !== 'scalar')?.path ||
            effectiveSchemaNodes.find((node) => node.node_kind === 'object' && node.path !== '$')?.path ||
            effectiveSchemaNodes.find((node) => node.path !== '$')?.path

        if (meaningfulPath) {
            const cleaned = meaningfulPath
                .replace(/^\$\./, '')
                .replace(/\[\*\]/g, '')
                .split('.')
                .filter(Boolean)
                .slice(-2)
                .join('_')
            if (cleaned) return cleaned
        }

        const fileName = file?.name || existingSource?.config?.filename || 'json_source'
        return fileName.replace(/\.json$/i, '')
    }, [effectiveSchemaNodes, file?.name, existingSource?.config?.filename])

    const normalizePath = (path: string) => path.trim()
    const isLikelyJsonPath = (path: string) => {
        const value = normalizePath(path)
        if (!value.startsWith('$')) return false
        // MVP validator: allow "$", dot-segments and wildcard arrays.
        return /^\$(\.[^.\[\]]+|\[\*\])*$/.test(value)
    }

    const combineBaseAndColumnPath = (basePath: string, columnPath: string) => {
        const base = normalizePath(basePath)
        const col = normalizePath(columnPath)
        if (!col.startsWith('$')) return col
        if (col === '$') return base
        if (col.startsWith('$[')) return `${base}${col.slice(1)}`
        if (col.startsWith('$.')) return `${base}.${col.slice(2)}`
        return col
    }

    const validateBasePath = (path: string) => {
        const value = normalizePath(path)
        if (!value) return 'Путь не должен быть пустым'
        if (!isLikelyJsonPath(value)) return 'Некорректный формат JSON path'
        if (effectiveSchemaNodes.length > 0 && arrayBasePathOptions.length > 0 && !arrayBasePathSet.has(value)) {
            return 'Путь таблицы должен указывать на валидный путь элемента массива из схемы'
        }
        return null
    }

    const validateColumnPath = (table: MappingTable, path: string) => {
        const value = normalizePath(path)
        if (!value) return 'Путь не должен быть пустым'
        if (!isLikelyJsonPath(value)) return 'Некорректный формат JSON path'
        if (effectiveSchemaNodes.length > 0) {
            const absolutePath = combineBaseAndColumnPath(table.base_path, value)
            if (!schemaPathSet.has(absolutePath)) {
                return 'Путь колонки не найден в snapshot схемы'
            }
        }
        return null
    }

    const normalizeBasePrefix = (basePath: string) => {
        const value = normalizePath(basePath)
        return value.endsWith('[*]') ? value.slice(0, -3) : value
    }

    const getBasePathVariants = (basePath: string) => {
        const base = normalizePath(basePath)
        const noWildcard = base.replace(/\[\*\]/g, '')
        const variants = [
            base,
            noWildcard,
            noWildcard ? `${noWildcard}[*]` : '',
        ].filter(Boolean)
        return Array.from(new Set(variants))
    }

    const isPathUnderBasePath = (basePath: string, absolutePath: string) => {
        const variants = getBasePathVariants(basePath)
        return variants.some((variant) => (
            absolutePath === variant || absolutePath.startsWith(`${variant}.`)
        ))
    }

    const toRelativePath = (basePath: string, absolutePath: string) => {
        if (!absolutePath.startsWith('$')) return absolutePath
        const variants = getBasePathVariants(basePath)
        for (const variant of variants) {
            if (absolutePath === variant) {
                return '$'
            }
            if (absolutePath.startsWith(`${variant}.`)) {
                return `$.${absolutePath.slice(variant.length + 1)}`
            }
        }
        return absolutePath
    }

    const mapSchemaTypeToColumnType = (types: string[]) => {
        if (types.includes('number')) return 'number'
        if (types.includes('boolean')) return 'boolean'
        if (types.includes('date')) return 'date'
        return 'text'
    }

    const deriveColumnNameFromPath = (path: string) => {
        const normalized = normalizePath(path)
            .replace(/^\$\./, '')
            .replace(/\[\*\]/g, '')
        const segments = normalized.split('.').filter(Boolean)
        const last = (segments[segments.length - 1] || 'column').toLowerCase()
        const canonical = FIELD_ALIASES[last] || last
        return canonical.replace(/[^\w\u0400-\u04FF]+/g, '_')
    }

    const splitRelativePath = (path: string) => {
        const normalized = normalizePath(path).replace(/^\$\./, '')
        const segments = normalized.split('.').filter(Boolean)
        const leaf = segments[segments.length - 1] || ''
        const parent = segments.slice(0, -1).join('.')
        return { parent, leaf }
    }

    const normalizeSchemaFieldOptions = (options: SchemaFieldOption[]) => {
        const byKey = new Map<string, SchemaFieldOption>()
        for (const option of options) {
            const { parent, leaf } = splitRelativePath(option.relativePath)
            const canonicalLeaf = FIELD_ALIASES[leaf.toLowerCase()] || leaf.toLowerCase()
            const key = `${parent}::${canonicalLeaf}`
            const existing = byKey.get(key)
            if (!existing) {
                byKey.set(key, option)
                continue
            }
            const currentIsNonAscii = /[^\x00-\x7F]/.test(splitRelativePath(option.relativePath).leaf)
            const existingIsNonAscii = /[^\x00-\x7F]/.test(splitRelativePath(existing.relativePath).leaf)
            if (existingIsNonAscii && !currentIsNonAscii) {
                byKey.set(key, option)
            }
        }
        return Array.from(byKey.values())
    }

    const getSchemaFieldOptionsForTable = (table: MappingTable): SchemaFieldOption[] => {
        const rawOptions = effectiveSchemaNodes
            .filter((node) => node.node_kind === 'scalar' && isPathUnderBasePath(table.base_path, node.path))
            .map((node) => ({
                absolutePath: node.path,
                relativePath: toRelativePath(table.base_path, node.path),
                inferredType: mapSchemaTypeToColumnType(node.value_types),
            }))
            // Keep only scalar columns from the current row object,
            // excluding nested arrays that should be normalized into child tables.
            .filter((opt) => !opt.relativePath.includes('[*]'))
            .filter((opt, idx, arr) => arr.findIndex((i) => i.relativePath === opt.relativePath) === idx)
            .slice(0, 300)
        return normalizeSchemaFieldOptions(rawOptions)
    }

    const buildAutoMappingFromSchema = (nodes: SchemaNode[]): MappingTable[] => {
        const rowObjectPaths = nodes
            .filter((n) => n.node_kind === 'object' && n.path.endsWith('[*]') && n.path !== '$')
            .map((n) => n.path)
        const groupArrayPaths = nodes
            .filter((n) => n.node_kind === 'array' && n.path.endsWith('[*]'))
            .map((n) => n.path)
            .filter((path) => rowObjectPaths.some((rowPath) => rowPath.startsWith(`${path}[*]`)))
        const arrayNodes = nodes.filter((n) => n.node_kind === 'array')
        const basePathEntries = rowObjectPaths.length > 0
            ? [
                ...rowObjectPaths.map((path) => ({ path, kind: 'row' as const })),
                ...groupArrayPaths.map((path) => ({ path, kind: 'group' as const })),
            ]
            : arrayNodes.length > 0
                ? arrayNodes.map((n) => ({ path: n.path.endsWith('[*]') ? n.path : `${n.path}[*]`, kind: 'row' as const }))
                : [{ path: '$', kind: 'row' as const }]

        const uniqueBasePaths = Array.from(new Map(basePathEntries.map((entry) => [entry.path, entry])).values())
        const safeName = (value: string) => {
            const normalized = value.replace(/^\$\./, '').replace(/\[\*\]/g, '')
            const segments = normalized.split('.').filter(Boolean)
            const tail = segments[segments.length - 1] || 'table'
            return tail.replace(/[^\w\u0400-\u04FF]+/g, '_') || 'table'
        }
        const toIdentifier = (value: string, fallback: string) => {
            const cleaned = value
                .toLowerCase()
                .replace(/[^\w\u0400-\u04FF]+/g, '_')
                .replace(/^_+|_+$/g, '')
            return cleaned || fallback
        }
        const isChildPathOf = (parentPath: string, childPath: string) =>
            childPath !== parentPath
            && (
                childPath.startsWith(`${parentPath}.`)
                || childPath.startsWith(`${parentPath}[*]`)
            )

        const usedPkColumns = new Set<string>()
        const usedTableIds = new Set<string>()
        const tables = uniqueBasePaths.map((entry, idx) => {
            const basePath = entry.path
            const baseName = safeName(basePath)
            const tableName = entry.kind === 'group' ? `${baseName}_group` : baseName
            let tableId = toIdentifier(tableName, `table_${idx + 1}`)
            while (usedTableIds.has(tableId)) {
                tableId = `${tableId}_${idx + 1}`
            }
            usedTableIds.add(tableId)
            const tableIdentifier = toIdentifier(tableName || tableId, tableId)
            let pkColumn = `${tableIdentifier}_id`
            while (usedPkColumns.has(pkColumn)) {
                pkColumn = `${tableIdentifier}_${idx + 1}_id`
            }
            usedPkColumns.add(pkColumn)
            const fieldOptions = nodes
                .filter((node) => node.node_kind === 'scalar' && isPathUnderBasePath(basePath, node.path))
                .map((node) => ({
                    relativePath: toRelativePath(basePath, node.path),
                    inferredType: mapSchemaTypeToColumnType(node.value_types),
                }))
                .filter((option) => !option.relativePath.includes('[*]'))
                .filter((option, optionIdx, arr) => arr.findIndex((x) => x.relativePath === option.relativePath) === optionIdx)
            const normalizedFieldOptions = normalizeSchemaFieldOptions(fieldOptions)

            const usedColumnNames = new Set<string>()
            const columns: MappingColumn[] = normalizedFieldOptions.map((option, cIdx) => {
                let columnName = deriveColumnNameFromPath(option.relativePath) || `column_${cIdx + 1}`
                while (usedColumnNames.has(columnName)) {
                    columnName = `${columnName}_${cIdx + 1}`
                }
                usedColumnNames.add(columnName)
                return {
                    name: columnName,
                    type: option.inferredType,
                    path: option.relativePath,
                    nullable: true,
                    description: describeDataColumn(tableId, tableName || tableId, option.relativePath),
                }
            })

            return {
                id: tableId,
                name: tableName || tableId,
                base_path: basePath,
                pk: { column: pkColumn, strategy: 'surrogate_uuid' },
                fk: [],
                columns,
            }
        })

        return tables.map((table) => {
            const parentCandidates = tables
                .filter((candidate) => candidate.base_path !== table.base_path)
                .filter((candidate) => isChildPathOf(candidate.base_path, table.base_path))
                .sort((a, b) => b.base_path.length - a.base_path.length)

            const parent = parentCandidates[0]
            if (!parent) {
                return table
            }

            const parentPk = parent.pk?.column || `${parent.id}_id`
            const reservedNames = new Set<string>([
                ...(table.columns || []).map((col) => col.name),
                table.pk?.column || '',
            ])
            let fkColumn = parentPk
            if (reservedNames.has(fkColumn)) {
                const parentName = toIdentifier(parent.name || parent.id, parent.id)
                fkColumn = `${parentName}_ref_id`
                let suffix = 2
                while (reservedNames.has(fkColumn)) {
                    fkColumn = `${parentName}_ref_${suffix}_id`
                    suffix += 1
                }
            }
            const fkEntry = {
                column: fkColumn,
                ref_table: parent.id,
                ref_column: parentPk,
            }

            // Keep only one parent FK for now (MVP): nearest ancestor array table.
            return {
                ...table,
                fk: [fkEntry],
            }
        })
    }

    const updateColumnSchemaField = (
        tableId: string,
        columnIndex: number,
        selectedPath: string
    ) => {
        setMappingTables((prev) =>
            prev.map((table) => {
                if (table.id !== tableId) return table
                const nextColumns = [...table.columns]
                const current = nextColumns[columnIndex]
                if (!current) return table
                const options = getSchemaFieldOptionsForTable(table)
                const selected = options.find((opt) => opt.relativePath === selectedPath)
                nextColumns[columnIndex] = {
                    ...current,
                    path: selectedPath,
                    // Auto-set both name and type from selected schema field;
                    // user can still adjust them manually afterwards.
                    name: deriveColumnNameFromPath(selectedPath),
                    type: selected?.inferredType || current.type,
                    description: describeDataColumn(table.id, table.name, selectedPath),
                }
                return { ...table, columns: nextColumns }
            })
        )
    }

    const mappingWarnings = useMemo(() => {
        const warnings: string[] = []
        mappingTables.forEach((table) => {
            const basePathError = validateBasePath(table.base_path)
            if (basePathError) warnings.push(`Таблица "${table.name}": ${basePathError}`)
            if (!table.name.trim()) warnings.push(`Таблица "${table.id}" без имени`)
            table.columns.forEach((column, idx) => {
                if (!column.name.trim()) {
                    warnings.push(`Таблица "${table.name}": колонка #${idx + 1} без имени`)
                }
                const pathError = validateColumnPath(table, column.path)
                if (pathError) {
                    warnings.push(`Таблица "${table.name}" / колонка "${column.name || `#${idx + 1}`}": ${pathError}`)
                }
            })
        })
        return warnings
    }, [mappingTables, effectiveSchemaNodes])

    const buildQuickSchemaPreview = (raw: any): SchemaNode[] => {
        const nodes: SchemaNode[] = []
        const nodeByPath = new Map<string, SchemaNode>()
        const maxNodes = 200
        const arraySampleSize = 20

        const valueType = (value: any) => {
            if (value === null || value === undefined) return 'null'
            if (Array.isArray(value)) return 'array'
            if (typeof value === 'boolean') return 'boolean'
            if (typeof value === 'number') return 'number'
            if (typeof value === 'string') return 'string'
            if (typeof value === 'object') return 'object'
            return 'unknown'
        }

        const pushNode = (path: string, node_kind: string, types: string[], cardinality?: string) => {
            if (nodes.length >= maxNodes && !nodeByPath.has(path)) return
            const existing = nodeByPath.get(path)
            if (existing) {
                const mergedTypes = Array.from(new Set([...(existing.value_types || []), ...types]))
                const mergedCardinality = existing.cardinality === cardinality ? existing.cardinality : (existing.cardinality || cardinality)
                existing.value_types = mergedTypes
                existing.cardinality = mergedCardinality
                return
            }
            const created: SchemaNode = { path, node_kind, value_types: Array.from(new Set(types)), cardinality }
            nodeByPath.set(path, created)
            nodes.push(created)
        }

        const walk = (value: any, path: string) => {
            if (nodes.length >= maxNodes) return
            if (Array.isArray(value)) {
                pushNode(path, 'array', ['array'], '0..N')
                if (value.length > 0) {
                    value.slice(0, arraySampleSize).forEach((item) => {
                        walk(item, `${path}[*]`)
                    })
                } else {
                    pushNode(`${path}[*]`, 'item', ['unknown'])
                }
                return
            }
            if (value && typeof value === 'object') {
                pushNode(path, 'object', ['object'], '1')
                Object.entries(value).forEach(([key, nested]) => {
                    walk(nested, `${path}.${key}`)
                })
                return
            }
            pushNode(path, 'scalar', [valueType(value)], value == null ? '0..1' : '1')
        }

        walk(raw, '$')
        return nodes
    }

    // Load existing data in edit mode
    useEffect(() => {
        if (mode === 'edit' && existingSource && open) {
            const config = existingSource.config
            const tables = normalizeMappingTables(config.mapping_spec?.tables)
            const nodes = normalizeSchemaNodes(config.schema_snapshot?.nodes)
            setMappingTables(tables)
            setSchemaNodes(nodes)
            setActiveTableId(tables[0]?.id || '')
        }
    }, [mode, existingSource, open])

    useEffect(() => {
        if (!activeTableId && mappingTables.length > 0) {
            setActiveTableId(mappingTables[0].id)
        }
        if (activeTableId && mappingTables.length > 0 && !mappingTables.some((t) => t.id === activeTableId)) {
            setActiveTableId(mappingTables[0].id)
        }
    }, [activeTableId, mappingTables])

    useEffect(() => {
        if (!open || !file) {
            setQuickSchemaNodes([])
            setQuickSchemaError(null)
            setQuickJsonData(null)
            setExpandedJsonNodes(new Set(['$']))
            return
        }

        let cancelled = false
        const parseFile = async () => {
            try {
                const text = await file.text()
                const parsed = JSON.parse(text)
                if (!cancelled) {
                    setQuickSchemaNodes(buildQuickSchemaPreview(parsed))
                    setQuickSchemaError(null)
                    setQuickJsonData(parsed)
                    setExpandedJsonNodes(new Set(['$', '$.data']))
                }
            } catch {
                if (!cancelled) {
                    setQuickSchemaNodes([])
                    setQuickSchemaError('Не удалось распарсить JSON. Проверьте формат файла.')
                    setQuickJsonData(null)
                    setExpandedJsonNodes(new Set(['$']))
                }
            }
        }
        parseFile()

        return () => {
            cancelled = true
        }
    }, [open, file])

    useEffect(() => {
        if (!open || !file || quickSchemaNodes.length === 0 || quickSchemaError) {
            return
        }
        const fileKey = `${file.name}:${file.size}:${file.lastModified}`
        if (autoGeneratedFileKey === fileKey) {
            return
        }

        const generatedTables = buildAutoMappingFromSchema(quickSchemaNodes)
        if (generatedTables.length > 0) {
            setMappingTables(generatedTables)
            setActiveTableId(generatedTables[0].id)
        }
        setAutoGeneratedFileKey(fileKey)
    }, [open, file, quickSchemaNodes, quickSchemaError, autoGeneratedFileKey])

    const updateTableField = (tableId: string, field: 'name' | 'base_path', value: string) => {
        setMappingTables((prev) =>
            prev.map((table) => (table.id === tableId ? { ...table, [field]: value } : table))
        )
    }

    const updateColumnField = (
        tableId: string,
        columnIndex: number,
        field: keyof MappingColumn,
        value: string | boolean
    ) => {
        setMappingTables((prev) =>
            prev.map((table) => {
                if (table.id !== tableId) return table
                const nextColumns = [...table.columns]
                const current = nextColumns[columnIndex]
                if (!current) return table
                nextColumns[columnIndex] = { ...current, [field]: value }
                return { ...table, columns: nextColumns }
            })
        )
    }

    const addColumn = (tableId: string) => {
        setPendingColumnScrollTableId(tableId)
        setMappingTables((prev) =>
            prev.map((table) => {
                if (table.id !== tableId) return table
                return {
                    ...table,
                    columns: [
                        ...table.columns,
                        {
                            name: `column_${table.columns.length + 1}`,
                            type: 'text',
                            path: '$',
                            nullable: true,
                            description: describeDataColumn(table.id, table.name, '$'),
                        },
                    ],
                }
            })
        )
    }

    useEffect(() => {
        if (!pendingColumnScrollTableId || activeTable?.id !== pendingColumnScrollTableId) return
        requestAnimationFrame(() => {
            if (activeColumnsScrollRef.current) {
                activeColumnsScrollRef.current.scrollTop = activeColumnsScrollRef.current.scrollHeight
            }
            setPendingColumnScrollTableId(null)
        })
    }, [mappingTables, pendingColumnScrollTableId, activeTable?.id])

    const removeColumn = (tableId: string, columnIndex: number) => {
        setMappingTables((prev) =>
            prev.map((table) => {
                if (table.id !== tableId) return table
                return {
                    ...table,
                    columns: table.columns.filter((_, idx) => idx !== columnIndex),
                }
            })
        )
    }

    const addTable = () => {
        const nextId = `table_${mappingTables.length + 1}`
        setMappingTables((prev) => [
            ...prev,
            {
                id: nextId,
                name: nextId,
                base_path: arrayBasePathOptions[0] || '$',
                pk: { column: `${nextId}_id`, strategy: 'surrogate_uuid' },
                fk: [],
                columns: [],
            },
        ])
        setActiveTableId(nextId)
    }

    const parseBasePathTokens = (path: string) => {
        if (!path.startsWith('$')) return []
        const tokens: string[] = []
        let rest = path.slice(1)
        while (rest.length > 0) {
            if (rest.startsWith('.')) {
                rest = rest.slice(1)
                const match = rest.match(/^[^.\[]+/)
                if (match) {
                    tokens.push(match[0])
                    rest = rest.slice(match[0].length)
                } else {
                    break
                }
            } else if (rest.startsWith('[*]')) {
                tokens.push('[*]')
                rest = rest.slice(3)
            } else {
                break
            }
        }
        return tokens
    }

    const resolveItemsByBasePath = (root: any, basePath: string): any[] => {
        const tokens = parseBasePathTokens(basePath)
        if (tokens.length === 0) return []
        let current: any[] = [root]
        for (const token of tokens) {
            const next: any[] = []
            for (const node of current) {
                if (token === '[*]') {
                    if (Array.isArray(node)) next.push(...node)
                    continue
                }
                if (node && typeof node === 'object' && token in node) {
                    next.push((node as any)[token])
                }
            }
            current = next
            if (current.length === 0) break
        }
        const flattened: any[] = []
        const collectObjects = (value: any) => {
            if (Array.isArray(value)) {
                value.forEach(collectObjects)
                return
            }
            if (value && typeof value === 'object') {
                flattened.push(value)
            }
        }
        current.forEach(collectObjects)
        return flattened
    }

    const extractRelativeValue = (obj: Record<string, any>, relativePath: string) => {
        const valuePath = normalizePath(relativePath)
        if (!valuePath || valuePath === '$') return obj
        if (!valuePath.startsWith('$.')) return null
        const segments = valuePath.slice(2).split('.').filter(Boolean)
        let current: any = obj
        for (const segment of segments) {
            if (segment.endsWith('[*]')) {
                const key = segment.slice(0, -3)
                if (!current || typeof current !== 'object' || !(key in current)) return null
                const arr = current[key]
                return Array.isArray(arr) ? JSON.stringify(arr) : null
            }
            if (!current || typeof current !== 'object' || !(segment in current)) return null
            current = current[segment]
        }
        if (Array.isArray(current) || (current && typeof current === 'object')) {
            return JSON.stringify(current)
        }
        return current
    }

    /** Deterministic UUID-like id for preview rows (matches no backend rows; for UI only). */
    const stablePreviewPk = (tableId: string, rowIdx: number) => {
        let h = 0
        for (let i = 0; i < tableId.length; i++) h = ((h << 5) - h + tableId.charCodeAt(i)) | 0
        const n = ((h >>> 0) ^ rowIdx) >>> 0
        const tail = (n.toString(16) + (rowIdx * 65537).toString(16)).padEnd(12, '0').slice(0, 12)
        return `00000000-0000-4000-8000-${tail}`
    }

    const jsonContains = (parent: any, target: any): boolean => {
        if (parent === target) return true
        if (Array.isArray(parent)) {
            for (const el of parent) {
                if (jsonContains(el, target)) return true
            }
            return false
        }
        if (parent && typeof parent === 'object') {
            for (const v of Object.values(parent)) {
                if (jsonContains(v, target)) return true
            }
        }
        return false
    }

    const activeTablePreview = useMemo(() => {
        if (!activeTable) return null

        const sourceTables = (existingSource as any)?.content?.tables
        if (Array.isArray(sourceTables) && sourceTables.length > 0) {
            const byName = sourceTables.find((t: any) => t?.name === activeTable.name)
            const byId = sourceTables.find((t: any) => t?.id === activeTable.id)
            const table = byName || byId
            if (table) {
                return {
                    columns: Array.isArray(table.columns) ? table.columns : [],
                    rows: Array.isArray(table.rows) ? table.rows : [],
                    rowCount: table.row_count ?? (Array.isArray(table.rows) ? table.rows.length : 0),
                    source: 'existing',
                }
            }
        }

        if (!quickJsonData) return null

        const pkColumn = activeTable.pk?.column || `${activeTable.id}_id`
        const fkEntries = activeTable.fk || []
        const hasMappingCols = activeTable.columns.length > 0
        const hasSurrogateCols = Boolean(pkColumn) || fkEntries.length > 0
        if (!hasMappingCols && !hasSurrogateCols) return null

        const items = resolveItemsByBasePath(quickJsonData, activeTable.base_path)
        const parentTableByRef = (refTable: string) => mappingTables.find((t) => t.id === refTable)

        const rows = items.slice(0, 100).map((item, idx) => {
            const row: Record<string, any> = {}
            row[pkColumn] = stablePreviewPk(activeTable.id, idx)

            for (const fk of fkEntries) {
                const pt = parentTableByRef(fk.ref_table)
                let fkVal: string | null = null
                if (pt) {
                    const parents = resolveItemsByBasePath(quickJsonData, pt.base_path)
                    const pi = parents.findIndex((p) => jsonContains(p, item))
                    if (pi >= 0) fkVal = stablePreviewPk(pt.id, pi)
                }
                row[fk.column] = fkVal ?? ''
            }

            activeTable.columns.forEach((col) => {
                row[col.name] = extractRelativeValue(item, col.path)
            })
            return row
        })

        const previewColumns = [
            {
                name: pkColumn,
                type: 'text',
                surrogate: 'pk' as const,
                description: `Суррогатный первичный ключ (PK) таблицы «${activeTable.name}» (id=${activeTable.id}).`,
            },
            ...fkEntries.map((f) => ({
                name: f.column,
                type: 'text',
                surrogate: 'fk' as const,
                description: `Внешний ключ (FK) на таблицу «${f.ref_table}», столбец ${f.ref_column}; дочерняя таблица «${activeTable.name}» (id=${activeTable.id}).`,
            })),
            ...activeTable.columns.map((c) => ({
                name: c.name,
                type: c.type,
                description: c.description?.trim() || describeDataColumn(activeTable.id, activeTable.name, c.path),
            })),
        ]

        return {
            columns: previewColumns,
            rows,
            rowCount: items.length,
            source: 'quick',
        }
    }, [activeTable, existingSource, quickJsonData, mappingTables])

    const toggleJsonNode = (path: string) => {
        setExpandedJsonNodes((prev) => {
            const next = new Set(prev)
            if (next.has(path)) next.delete(path)
            else next.add(path)
            return next
        })
    }

    const formatJsonPrimitive = (value: any): string => {
        if (value === null) return 'null'
        if (typeof value === 'string') return `"${value}"`
        if (typeof value === 'number' || typeof value === 'boolean') return String(value)
        return String(value)
    }

    const renderJsonNode = (key: string, value: any, path: string, depth: number): JSX.Element => {
        const indent = { paddingLeft: `${depth * 14}px` }
        const isArray = Array.isArray(value)
        const isObject = value && typeof value === 'object' && !isArray
        const isContainer = isArray || isObject
        const isExpanded = expandedJsonNodes.has(path)
        const summary = isArray
            ? `[${value.length}]`
            : isObject
                ? `{${Object.keys(value).length}}`
                : formatJsonPrimitive(value)

        if (!isContainer) {
            return (
                <div key={path} className="py-0.5 text-xs" style={indent}>
                    <span className="text-muted-foreground">{key}: </span>
                    <span>{summary}</span>
                </div>
            )
        }

        const entries = isArray
            ? value.map((item: any, idx: number) => [`[${idx}]`, item] as const).slice(0, 100)
            : Object.entries(value).slice(0, 100)

        return (
            <div key={path}>
                <button
                    type="button"
                    className="w-full flex items-center gap-1 py-0.5 text-xs hover:bg-muted/40 rounded"
                    style={indent}
                    onClick={() => toggleJsonNode(path)}
                >
                    {isExpanded ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
                    <span className="text-muted-foreground">{key}: </span>
                    <span>{summary}</span>
                </button>
                {isExpanded && (
                    <div>
                        {entries.map(([childKey, childValue]) =>
                            renderJsonNode(String(childKey), childValue, `${path}.${childKey}`, depth + 1)
                        )}
                        {((isArray && value.length > entries.length) || (isObject && Object.keys(value).length > entries.length)) && (
                            <div className="py-0.5 text-xs text-muted-foreground" style={{ paddingLeft: `${(depth + 1) * 14}px` }}>
                                ... еще элементы
                            </div>
                        )}
                    </div>
                )}
            </div>
        )
    }

    const removeTable = (tableId: string) => {
        setMappingTables((prev) => prev.filter((table) => table.id !== tableId))
    }

    const startTableRename = (tableId: string) => {
        const table = mappingTables.find((t) => t.id === tableId)
        if (!table) return
        setActiveTableId(tableId)
        setEditingTableId(tableId)
        setEditingTableName(table.name)
    }

    const commitTableRename = (tableId: string) => {
        const table = mappingTables.find((t) => t.id === tableId)
        if (!table) return
        const nextName = editingTableName.trim()
        if (nextName) {
            updateTableField(tableId, 'name', nextName)
        }
        setEditingTableId(null)
        setEditingTableName('')
    }

    const cancelTableRename = () => {
        setEditingTableId(null)
        setEditingTableName('')
    }

    const handleSubmit = async () => {
        const isEditMode = mode === 'edit' && !!existingSource
        if (mappingTables.length > 0 && mappingWarnings.length > 0) {
            notify.error('Исправьте ошибки мэппинга перед сохранением')
            return
        }

        const hasExistingFile = !!existingSource?.config?.file_id
        if (!file && !hasExistingFile) {
            notify.error('Выберите JSON файл')
            return
        }

        let fileMeta = {
            file_id: existingSource?.config?.file_id,
            filename: existingSource?.config?.filename,
            mime_type: existingSource?.config?.mime_type,
            size_bytes: existingSource?.config?.size_bytes,
        }

        if (file) {
            setIsUploading(true)
            try {
                notify.info('Загрузка файла...')
                const uploadResponse = await filesAPI.upload(file)
                const uploadedFile = uploadResponse.data
                fileMeta = {
                    file_id: uploadedFile.file_id,
                    filename: uploadedFile.filename,
                    mime_type: uploadedFile.mime_type,
                    size_bytes: uploadedFile.size_bytes,
                }
                notify.success(`Файл "${file.name}" загружен`)
            } catch (error) {
                notify.error('Не удалось загрузить файл')
                console.error('File upload error:', error)
                return
            } finally {
                setIsUploading(false)
            }
        }

        const config: any = {
            file_id: fileMeta.file_id,
            filename: fileMeta.filename,
            mime_type: fileMeta.mime_type,
            size_bytes: fileMeta.size_bytes,
            json_path: mappingTables[0]?.base_path || existingSource?.config?.json_path || '$',
        }
        if (mappingTables.length > 0) {
            config.mapping_spec = buildMappingSpecPayload()
            config.generation_meta = {
                ...(existingSource?.config?.generation_meta || {}),
                generated_by: 'user_edited',
            }
        }
        if (schemaNodes.length > 0) {
            config.schema_snapshot = {
                ...(existingSource?.config?.schema_snapshot || {}),
                version: existingSource?.config?.schema_snapshot?.version || '1.0',
                nodes: schemaNodes,
            }
        }

        const metadata: any = {
            name: derivedSourceName,
        }

        if (isEditMode && existingSource) {
            await update(existingSource.id, config, metadata)
            return
        }

        await create(config, metadata)
    }

    const dialogTitle = 'JSON источник'
    const dialogDescription = 'Настройка источника, схемы и мэппинга JSON'
    const isValid = !!derivedSourceName && (!!file || !!existingSource?.config?.file_id)

    return (
        <BaseSourceDialog
            open={open}
            onOpenChange={onOpenChange}
            title={dialogTitle}
            description={dialogDescription}
            icon={<FileJson className="h-5 w-5 text-yellow-500" />}
            isLoading={isLoading || isUploading}
            isValid={isValid}
            onSubmit={handleSubmit}
            submitLabel="Сохранить"
            className="w-[calc(100vw-2rem)] max-w-[calc(100vw-2rem)] h-[calc(100vh-2rem)]"
            contentClassName="overflow-hidden"
        >
            <div className="h-full min-h-0 flex flex-col gap-4">
                {mappingWarnings.length > 0 && (
                    <div className="rounded-lg border border-destructive/50 bg-destructive/5 p-3">
                        <p className="text-sm font-medium text-destructive">Ошибки мэппинга</p>
                        <ul className="mt-1 list-disc pl-4 space-y-1 text-xs text-destructive">
                            {mappingWarnings.slice(0, 6).map((warning, idx) => (
                                <li key={`${warning}-${idx}`}>{warning}</li>
                            ))}
                        </ul>
                        {mappingWarnings.length > 6 && (
                            <p className="text-xs text-destructive mt-1">
                                И еще {mappingWarnings.length - 6} ошибок.
                            </p>
                        )}
                    </div>
                )}

                <div className="grid gap-4 lg:grid-cols-2 flex-1 min-h-0">
                    <div className="p-3 flex flex-col min-h-0 gap-3">
                        <div className="space-y-2">
                            <Input
                                id="json-file"
                                type="file"
                                accept=".json"
                                aria-label={mode === 'edit' ? 'Заменить JSON файл' : 'Выберите JSON файл'}
                                onChange={(e) => setFile(e.target.files?.[0] || null)}
                                className="cursor-pointer"
                            />
                            {file && (
                                <p className="text-xs text-muted-foreground">
                                    Выбран: {file.name} ({(file.size / 1024).toFixed(2)} KB)
                                </p>
                            )}
                            {!file && existingSource?.config?.filename && (
                                <p className="text-xs text-muted-foreground">
                                    Текущий файл: {existingSource.config.filename}
                                </p>
                            )}
                        </div>
                        <div className="border-t pt-2 flex-1 min-h-0 flex flex-col gap-2">
                            <p className="text-sm font-medium">Предпросмотр JSON</p>
                            {quickSchemaError && (
                                <p className="text-xs text-destructive">{quickSchemaError}</p>
                            )}
                            {!quickJsonData ? (
                                <div className="flex-1 flex items-center justify-center text-xs text-muted-foreground border rounded">
                                    Загрузите JSON, чтобы увидеть структуру.
                                </div>
                            ) : (
                                <div className="flex-1 min-h-0 overflow-auto border rounded p-2 bg-muted/10 font-mono">
                                    {renderJsonNode('$', quickJsonData, '$', 0)}
                                </div>
                            )}
                        </div>
                    </div>

                    <div className="p-2.5 flex flex-col min-h-0 gap-2">
                        <div className="flex-1 min-h-0 flex flex-col p-2.5 gap-1.5">
                            <div className="flex items-center justify-between">
                                <p className="text-sm font-medium">Таблицы мэппинга</p>
                                <button
                                    type="button"
                                    className="h-7 w-7 inline-flex items-center justify-center rounded border text-primary hover:bg-primary/10"
                                    onClick={addTable}
                                    title="Добавить таблицу"
                                    aria-label="Добавить таблицу"
                                >
                                    <Plus className="h-4 w-4" />
                                </button>
                            </div>

                            {mappingTables.length === 0 ? (
                                <p className="text-xs text-muted-foreground">
                                    Мэппинг будет сгенерирован автоматически после первого создания/обновления.
                                </p>
                            ) : (
                                <div className="space-y-1.5 flex-1 min-h-0 flex flex-col">
                                    <div className="flex flex-wrap gap-1.5">
                                        {mappingTables.map((table) => (
                                            <div
                                                key={table.id}
                                                className={cn(
                                                    'flex items-center gap-1 px-1 py-0.5 rounded border',
                                                    activeTable?.id === table.id
                                                        ? 'bg-primary/10 border-primary'
                                                        : 'bg-background'
                                                )}
                                                onClick={() => setActiveTableId(table.id)}
                                            >
                                                {editingTableId === table.id ? (
                                                    <Input
                                                        autoFocus
                                                        className={cn(
                                                            'h-6 text-xs w-28',
                                                            activeTable?.id === table.id && 'border-primary'
                                                        )}
                                                        value={editingTableName}
                                                        onClick={(e) => e.stopPropagation()}
                                                        onChange={(e) => setEditingTableName(e.target.value)}
                                                        onBlur={() => commitTableRename(table.id)}
                                                        onKeyDown={(e) => {
                                                            if (e.key === 'Enter') {
                                                                e.preventDefault()
                                                                commitTableRename(table.id)
                                                            }
                                                            if (e.key === 'Escape') {
                                                                e.preventDefault()
                                                                cancelTableRename()
                                                            }
                                                        }}
                                                        placeholder="table_name"
                                                    />
                                                ) : (
                                                    <button
                                                        type="button"
                                                        className={cn(
                                                            'h-6 px-2 text-xs rounded',
                                                            activeTable?.id === table.id ? 'text-primary' : 'text-foreground'
                                                        )}
                                                        onClick={(e) => {
                                                            e.stopPropagation()
                                                            setActiveTableId(table.id)
                                                        }}
                                                    >
                                                        {table.name}
                                                    </button>
                                                )}
                                                <button
                                                    type="button"
                                                    className="h-7 w-7 rounded text-xs text-muted-foreground hover:bg-muted"
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        if (editingTableId === table.id) return
                                                        startTableRename(table.id)
                                                    }}
                                                    title="Переименовать таблицу"
                                                >
                                                    ✎
                                                </button>
                                                <button
                                                    type="button"
                                                    className="h-7 w-7 rounded text-xs text-destructive hover:bg-destructive/10"
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        removeTable(table.id)
                                                    }}
                                                    title="Удалить таблицу"
                                                >
                                                    ✕
                                                </button>
                                            </div>
                                        ))}
                                    </div>

                                    {activeTable && (
                                        <div className="space-y-2 border rounded p-2.5 flex-1 min-h-0 flex flex-col">
                                            <div className="grid grid-cols-[minmax(0,1fr)_auto] gap-1.5 items-end">
                                                <div className="space-y-1 min-w-0">
                                                    <Label>Base path</Label>
                                                    <select
                                                        value={activeTable.base_path}
                                                        onChange={(e) =>
                                                            updateTableField(activeTable.id, 'base_path', e.target.value)
                                                        }
                                                        className={cn(
                                                            'h-8 w-full rounded-md border border-input bg-background px-2 text-xs',
                                                            validateBasePath(activeTable.base_path) && 'border-destructive focus-visible:ring-destructive'
                                                        )}
                                                    >
                                                        {arrayBasePathOptions.length === 0 ? (
                                                            <option value="$">Нет узлов-массивов в схеме</option>
                                                        ) : (
                                                            arrayBasePathOptions.map((path) => (
                                                                <option key={path} value={path}>
                                                                    {path}
                                                                </option>
                                                            ))
                                                        )}
                                                        {!arrayBasePathSet.has(activeTable.base_path) && activeTable.base_path && (
                                                            <option value={activeTable.base_path}>{activeTable.base_path}</option>
                                                        )}
                                                    </select>
                                                    {validateBasePath(activeTable.base_path) && (
                                                        <p className="text-xs text-destructive">
                                                            {validateBasePath(activeTable.base_path)}
                                                        </p>
                                                    )}
                                                </div>
                                                <button
                                                    type="button"
                                                    className="h-8 w-8 inline-flex items-center justify-center rounded border text-primary hover:bg-primary/10"
                                                    onClick={() => addColumn(activeTable.id)}
                                                    title="Добавить столбец"
                                                    aria-label="Добавить столбец"
                                                >
                                                    <Plus className="h-4 w-4" />
                                                </button>
                                            </div>

                                            <div ref={activeColumnsScrollRef} className="flex-1 min-h-0 overflow-y-auto pr-1 space-y-1.5">
                                                {activeTable.columns.length === 0 ? (
                                                    <p className="text-xs text-muted-foreground">
                                                        У таблицы пока нет колонок из JSON.
                                                    </p>
                                                ) : (
                                                    activeTable.columns.map((column, colIdx) => {
                                                        const columnPathError = validateColumnPath(activeTable, column.path)
                                                        const schemaFieldOptions = getSchemaFieldOptionsForTable(activeTable)
                                                        return (
                                                            <div key={`${activeTable.id}-${colIdx}`} className="space-y-0.5">
                                                                <div className="grid grid-cols-12 gap-1.5 items-center">
                                                                    <select
                                                                        value={column.path}
                                                                        onChange={(e) =>
                                                                            updateColumnSchemaField(activeTable.id, colIdx, e.target.value)
                                                                        }
                                                                        className={cn(
                                                                            'col-span-5 h-8 rounded-md border border-input bg-background px-2 text-xs',
                                                                            columnPathError && 'border-destructive focus-visible:ring-destructive'
                                                                        )}
                                                                    >
                                                                        <option value="">Выберите поле схемы</option>
                                                                        {schemaFieldOptions.map((opt) => (
                                                                            <option key={`${activeTable.id}-${opt.relativePath}`} value={opt.relativePath}>
                                                                                {opt.relativePath}
                                                                            </option>
                                                                        ))}
                                                                        {!schemaFieldOptions.some((opt) => opt.relativePath === column.path) && column.path && (
                                                                            <option value={column.path}>{column.path}</option>
                                                                        )}
                                                                    </select>
                                                                    <Input
                                                                        className="col-span-4 h-8 text-xs"
                                                                        value={column.name}
                                                                        onChange={(e) =>
                                                                            updateColumnField(activeTable.id, colIdx, 'name', e.target.value)
                                                                        }
                                                                        placeholder="column_name"
                                                                    />
                                                                    <select
                                                                        value={column.type}
                                                                        onChange={(e) =>
                                                                            updateColumnField(activeTable.id, colIdx, 'type', e.target.value)
                                                                        }
                                                                        className="col-span-2 h-8 rounded-md border border-input bg-background px-2 text-xs"
                                                                    >
                                                                        <option value="text">text</option>
                                                                        <option value="number">number</option>
                                                                        <option value="boolean">boolean</option>
                                                                        <option value="date">date</option>
                                                                    </select>
                                                                    <button
                                                                        type="button"
                                                                        className="col-span-1 h-8 text-xs text-destructive hover:underline"
                                                                        onClick={() => removeColumn(activeTable.id, colIdx)}
                                                                    >
                                                                        ✕
                                                                    </button>
                                                                </div>
                                                                {columnPathError && (
                                                                    <p className="text-xs text-destructive">{columnPathError}</p>
                                                                )}
                                                            </div>
                                                        )
                                                    })
                                                )}
                                            </div>

                                            <div className="border-t pt-2 mt-1 flex-[0_0_34%] min-h-0 flex flex-col">
                                                <div className="flex items-center justify-between mb-1.5">
                                                    <p className="text-sm font-medium">Предпросмотр таблицы</p>
                                                    {activeTablePreview && (
                                                        <p className="text-xs text-muted-foreground">
                                                            {activeTablePreview.source === 'quick' ? 'Временный preview' : 'Текущие данные'} · {activeTablePreview.rowCount} строк
                                                        </p>
                                                    )}
                                                </div>

                                                {!activeTablePreview ? (
                                                    <div className="flex-1 flex items-center justify-center text-xs text-muted-foreground">
                                                        Нет данных для предпросмотра. Выберите файл или сохраните источник.
                                                    </div>
                                                ) : activeTablePreview.columns.length === 0 ? (
                                                    <div className="flex-1 flex items-center justify-center text-xs text-muted-foreground">
                                                        Добавьте колонки в мэппинг или задайте суррогатный ключ (PK), чтобы увидеть данные.
                                                    </div>
                                                ) : (
                                                    <div className="flex-1 min-h-0 overflow-auto border rounded">
                                                        <table className="w-full text-xs">
                                                            <thead className="bg-muted/50 sticky top-0 z-10">
                                                                <tr>
                                                                    {activeTablePreview.columns.map((col: any) => (
                                                                        <th
                                                                            key={col.name}
                                                                            title={typeof col.description === 'string' && col.description ? col.description : undefined}
                                                                            className="p-1.5 text-left font-medium border-b whitespace-nowrap"
                                                                        >
                                                                            {col.name}
                                                                            {col.surrogate === 'pk' && (
                                                                                <span className="ml-1 text-[10px] text-muted-foreground font-normal">PK</span>
                                                                            )}
                                                                            {col.surrogate === 'fk' && (
                                                                                <span className="ml-1 text-[10px] text-muted-foreground font-normal">FK</span>
                                                                            )}
                                                                            <span className="ml-1 text-muted-foreground font-normal">({col.type})</span>
                                                                        </th>
                                                                    ))}
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                {activeTablePreview.rows.slice(0, 200).map((row: any, rowIdx: number) => (
                                                                    <tr key={rowIdx} className="border-b hover:bg-muted/20">
                                                                        {activeTablePreview.columns.map((col: any) => (
                                                                            <td key={`${rowIdx}-${col.name}`} className="p-1.5 align-top max-w-[240px] truncate">
                                                                                {row?.[col.name] == null ? '' : String(row[col.name])}
                                                                            </td>
                                                                        ))}
                                                                    </tr>
                                                                ))}
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </BaseSourceDialog>
    )
}
