"""Add ChatMessage model for AI assistant

Revision ID: 649b30b035df
Revises: b11f1b4dcdbe
Create Date: 2026-01-27 13:12:29.316790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '649b30b035df'
down_revision = 'b11f1b4dcdbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_board_id'), 'chat_messages', ['board_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_index(op.f('idx_boards_project_id'), table_name='boards')
    op.drop_index(op.f('idx_boards_user_id'), table_name='boards')
    op.alter_column('comment_nodes', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_comment_nodes_author_id'), table_name='comment_nodes')
    op.drop_constraint(op.f('comment_nodes_id_fkey'), 'comment_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_nodes', 'nodes', ['id'], ['id'])
    op.alter_column('data_nodes', 'schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('data_nodes', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_nodes', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('edges', 'is_valid',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'true'::character varying"))
    op.drop_index(op.f('ix_edges_board_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_node'), table_name='edges')
    op.drop_index(op.f('ix_edges_target_node'), table_name='edges')
    op.drop_index(op.f('ix_nodes_board_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_type'), table_name='nodes')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.drop_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('widget_nodes', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('widget_nodes_id_fkey'), 'widget_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'widget_nodes', 'nodes', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widget_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('widget_nodes_id_fkey'), 'widget_nodes', 'nodes', ['id'], ['id'], ondelete='CASCADE')
    op.alter_column('widget_nodes', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_nodes_node_type'), 'nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_nodes_board_id'), 'nodes', ['board_id'], unique=False)
    op.create_index(op.f('ix_edges_target_node'), 'edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_edges_source_node'), 'edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_edges_board_id'), 'edges', ['board_id'], unique=False)
    op.alter_column('edges', 'is_valid',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'true'::character varying"))
    op.alter_column('data_nodes', 'parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('data_nodes', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_nodes', 'schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'comment_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('comment_nodes_id_fkey'), 'comment_nodes', 'nodes', ['id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_comment_nodes_author_id'), 'comment_nodes', ['author_id'], unique=False)
    op.alter_column('comment_nodes', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_boards_user_id'), 'boards', ['user_id'], unique=False)
    op.create_index(op.f('idx_boards_project_id'), 'boards', ['project_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_board_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
