"""Rename metadata to session_metadata in AgentSession

Revision ID: a23e270852e3
Revises: bb3675d28567
Create Date: 2026-01-27 19:22:30.906247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23e270852e3'
down_revision = 'bb3675d28567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
