"""Add AgentSession model for Multi-Agent Phase 2

Revision ID: bb3675d28567
Revises: 649b30b035df
Create Date: 2026-01-27 19:20:58.542602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3675d28567'
down_revision = '649b30b035df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
